### ISSUE TITLE
Add PR notification hook for rFOX PR opened event

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/rFOX#65]
We frequently miss the event of a PR being opened in this project, primarily because the hook that notifies discord is not set up for this project.

Set it up 👍

**Comment by 0xApotheosis** [comment]
Actioned:

<img width="841" alt="Screenshot 2024-06-11 at 10 46 04 AM" src="https://github.com/shapeshift/rFOX/assets/97164662/178ad6cc-879c-456f-9f83-ab82e81ce121">

<img width="644" alt="Screenshot 2024-06-11 at 10 46 12 AM" src="https://github.com/shapeshift/rFOX/assets/97164662/dbc75f92-7176-4651-9c43-da7ededceaf7">
