### ISSUE TITLE
CLI hot wallet - rune transaction and final data pinning

### ISSUE THREAD

**Issue by 0xean** [shapeshift/rFOX#71]
see https://github.com/shapeshift/rFOX/issues/58 for context

#### AC
1. get account number from unchained endpoint for hot wallet address
1. prompt user for IPFS hash they want to process
2. confirm with user the epoch of that IPFS data 
3. pull down IPFS data / json to process into RUNE transactions
4. sign all transactions and output to temp file in case of errors. (We can always retry transactions from this file, nonces can enforce the transactions that are already successfully executed so no risk in re-running all of them as long no shenanigans with the wallet - RETRY NOT IN SCOPE)
5. broadcast RUNE transactions.
6. If errors occur, prompt users to re-run from saved temp file of signed transactions. (re running not in scope, just let the user know)
7. persist tx hashes to IPFS and output ipfs hash (prompt user to post final hash to forum)

**Comment by kaladinlight** [comment]
Broke out further IPFS work into separate issue: https://github.com/shapeshift/rFOX/issues/75
